import base64
import io
import os
import zipfile
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent.parent
PREVIEW_DIR = BASE_DIR / "preview" / "section6"
SHARED_CSS = BASE_DIR / "preview" / "shared" / "styles.css"
CHARTS_DIR = BASE_DIR / "0.2. Pure'O Naturals Data" / "charts" / "section6"
OUTPUTS_DIR = BASE_DIR / "0.2. Pure'O Naturals Data" / "outputs"

DATA_FILES = [
    BASE_DIR / "0.2. Pure'O Naturals Data" / "output" / "high_volatility_products.csv",
    BASE_DIR / "0.2. Pure'O Naturals Data" / "output_ada" / "rolling_volatility.csv",
    BASE_DIR / "0.2. Pure'O Naturals Data" / "low_margin.csv",
    BASE_DIR / "0.2. Pure'O Naturals Data" / "output_ada" / "abc_classification.csv",
    BASE_DIR / "0.2. Pure'O Naturals Data" / "slow_movers.csv",
    BASE_DIR / "0.2. Pure'O Naturals Data" / "pricing_misalignment_top20.csv",
    BASE_DIR / "0.2. Pure'O Naturals Data" / "outputs" / "price_variance_statistics.csv",
]

FIGS = [
    CHARTS_DIR / "Figure_6_1_CV_Distribution.png",
    CHARTS_DIR / "Figure_6_2_Rolling_Volatility_By_Month.png",
    CHARTS_DIR / "Figure_6_3_Margin_Distribution.png",
    CHARTS_DIR / "Figure_6_4_ABC_Pareto.png",
    CHARTS_DIR / "Figure_6_5_Slow_Movers_DSLS.png",
    CHARTS_DIR / "Figure_6_6_Price_Variance_Top20.png",
]

DIST_DIR = BASE_DIR / "dist"


def embed_resources(html_path: Path, css_path: Path, figs: list[Path]) -> str:
    html = html_path.read_text(encoding="utf-8")
    css = css_path.read_text(encoding="utf-8")
    # Inline CSS
    html = html.replace("<link rel=\"stylesheet\" href=\"/preview/shared/styles.css\">", f"<style>{css}</style>")
    # Embed figures as data URIs
    for fp in figs:
        if fp.exists():
            b64 = base64.b64encode(fp.read_bytes()).decode("ascii")
            data_uri = f"data:image/png;base64,{b64}"
            html = html.replace(str(fp).replace(str(BASE_DIR), "").replace("\\", "/"), data_uri)
            # Also replace server-style src paths
            server_src = "/charts\\section6\\" + fp.name
            html = html.replace(server_src, data_uri)
    return html


def build_zip():
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    version = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_path = DIST_DIR / f"section6_package_{version}.zip"

    embedded_html = embed_resources(PREVIEW_DIR / "index.html", SHARED_CSS, FIGS)
    readme = f"""
Section 6 — Results & Findings (Pure'O Naturals)
Version: {version}

Contents:
- index_embedded.html (all resources inlined)
- charts/ (high-resolution PNG charts)
- data/ (source CSVs with attribution)
- style_guide.md (styling and print guidance)
- outputs/Section6_PureO_Naturals.pdf (exported PDF)

Dependencies:
- Chromium-based browser (Edge/Chrome) for PDF export
- Python 3.13 with PyPDF2 for metadata/bookmarks

History:
- Auto-generated by package_section6_assets.py on {datetime.now()}
""".strip()

    style_guide = (
        """
Section 6 Style Guide

- Fonts: Times New Roman, serif; headings bold
- Colors: Text #1f2937; captions #374151
- Layout: container max-width 960px, 16px padding
- Figures: full-width images, captions prefixed with Figure 6.x
- Print: @page A4 with 20mm margin; .page-break before each section
- TOC: anchors for sections and figures; links non-underlined in print
""".strip()
    )

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("index_embedded.html", embedded_html)
        z.writestr("README.md", readme)
        z.writestr("style_guide.md", style_guide)
        # Include high-res charts
        for fp in FIGS:
            if fp.exists():
                z.write(fp, arcname=f"charts/{fp.name}")
        # Include data files with attribution
        for df in DATA_FILES:
            if df.exists():
                z.write(df, arcname=f"data/{df.name}")
        # Include PDF if available
        pdf_path = OUTPUTS_DIR / "Section6_PureO_Naturals.pdf"
        if pdf_path.exists():
            z.write(pdf_path, arcname="outputs/Section6_PureO_Naturals.pdf")

    print(f"Package ready: {zip_path}")


if __name__ == "__main__":
    build_zip()